name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run Build
      run: cargo build --release --verbose
    - uses: actions/upload-artifact@v2
      with:
        name: uuid
        path: target/release/uuid
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run Build
      run: cargo build --release --verbose
    - uses: actions/upload-artifact@v2
      with:
        name: uuid
        path: target/release/uuid.exe
